plugins {
    id 'dev.architectury.loom' version '1.11-SNAPSHOT' apply false
    id 'architectury-plugin' version '3.4-SNAPSHOT'
    id 'com.gradleup.shadow' version '8.3.6' apply false
    id 'com.matthewprenger.cursegradle' version '1.4.0' apply false
    id 'com.modrinth.minotaur' version '2.8.4' apply false
    id 'com.diffplug.spotless' version '7.2.1' apply false
    id "com.dorongold.task-tree" version "4.0.1" apply false
}

allprojects {
    apply plugin: 'com.dorongold.task-tree'
}

architectury {
    minecraft = project.minecraft_version
}

allprojects {
    group = "me.ramidzkh"
    version = System.getenv("APPBOT_VERSION") ?: "0.0.0"
}

subprojects {
    apply plugin: 'dev.architectury.loom'
    apply plugin: 'architectury-plugin'
    apply plugin: 'com.diffplug.spotless'

    loom {
        silentMojangMappingsLicense()
    }

    dependencies {
        minecraft "net.minecraft:minecraft:$rootProject.minecraft_version"
        mappings loom.officialMojangMappings()
    }

    base {
        archivesName = "$rootProject.name-$project.name"
    }

    java {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    tasks.withType(JavaCompile).configureEach {
        options.release = 17
        options.encoding = "UTF-8"
    }

    /////////////
    // Spotless
    spotless {
        java {
            target("src/main/java/**/*.java")

            endWithNewline()
            leadingTabsToSpaces()
            removeUnusedImports()
            toggleOffOn()
            eclipse().configFile(rootProject.file("codeformat/codeformat.xml"))
            importOrderFile(rootProject.file("codeformat/ae2.importorder"))
        }

        format("json") {
            target("src/main/resources/**/*.json")
            prettier().config(parser: "json")
        }
    }
}

def copyOutputs = tasks.register('copyOutputs', Copy) {
    from(project(":forge").remapJar)
    into(layout.buildDirectory.dir('distributions'))
}

tasks.maybeCreate('build').dependsOn(copyOutputs)
