plugins {
    id 'dev.architectury.loom' version '1.11-SNAPSHOT'
    id 'com.diffplug.spotless' version '8.0.0'
}

group = "me.ramidzkh"
version = System.getenv("APPBOT_VERSION") ?: "0.0.0"

base {
    archivesName = "$project.name"
}

loom {
    silentMojangMappingsLicense()

    forge {
        mixinConfig("appbot.mixins.json")
    }

    runs {
        data {
            data()
            programArgs "--all", "--mod", "appbot"
            programArgs "--output", file("src/generated/resources").absolutePath
            programArgs "--existing", file("src/main/resources").absolutePath
        }
    }
}

repositories {
    exclusiveContent {
        forRepository {
            maven {
                name = "Modmaven"
                url = uri("https://modmaven.dev/")
            }
        }

        filter {
            includeGroup("appeng")
            includeGroup("vazkii.botania")
            includeGroup("vazkii.patchouli")
            includeGroup("mezz.jei")
        }
    }

    exclusiveContent {
        forRepository {
            maven {
                name = "theillusivec4"
                url = uri("https://maven.theillusivec4.top/")
            }
        }

        filter {
            includeGroup("top.theillusivec4.curios")
        }
    }

    exclusiveContent {
        forRepository {
            maven {
                name = "TerraformersMC"
                url = uri("https://maven.terraformersmc.com/")
            }
        }

        filter {
            includeGroup("dev.emi")
        }
    }

    exclusiveContent {
        forRepository {
            maven {
                name = "shedaniel"
                url = uri("https://maven.shedaniel.me/")
            }
        }

        filter {
            includeGroup("me.shedaniel")
            includeGroup("me.shedaniel.cloth")
        }
    }
}

dependencies {
    compileOnly("com.google.code.findbugs:jsr305:3.0.2")

    minecraft("net.minecraft:minecraft:$minecraft_version")
    mappings(loom.officialMojangMappings())
    forge("net.minecraftforge:forge:$forge_version")

    modImplementation("appeng:appliedenergistics2-forge:$ae2_version")
    modImplementation("vazkii.botania:Botania:$minecraft_version-$botania_version_forge")

    modCompileOnly("mezz.jei:jei-$minecraft_version-common-api:$jei_version")
    modCompileOnly("me.shedaniel:RoughlyEnoughItems-api:$rei_version")
    modCompileOnly("dev.emi:emi-forge:$emi_version:api")

    modRuntimeOnly("org.appliedenergistics:guideme:$guideme_version")
    modRuntimeOnly("vazkii.patchouli:Patchouli:$minecraft_version-$patchouli_version-FORGE")
    modRuntimeOnly("top.theillusivec4.curios:curios-forge:$curios_version+$minecraft_version")

    // dev: choose runtime xei mod(s)
    def xei = ["jei", "emi"]

    if (xei.remove("jei")) {
        modRuntimeOnly("mezz.jei:jei-$minecraft_version-forge:$jei_version") {
            transitive = false
        }
    }

    if (xei.remove("rei")) {
        modRuntimeOnly("me.shedaniel:RoughlyEnoughItems-forge:$rei_version")
    }

    if (xei.remove("emi")) {
        modRuntimeOnly("dev.emi:emi-forge:$emi_version")
    }

    if (!xei.isEmpty()) {
        throw new GradleException("Unknown xei mods: $xei")
    }
}

sourceSets {
    main {
        resources {
            srcDir(file("src/generated/resources"))
        }
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

tasks.withType(JavaCompile).configureEach {
    options.release = 17
    options.encoding = "UTF-8"
}

processResources {
    inputs.property 'version', project.version

    from file('LICENSE')
    exclude '.cache'

    filesMatching('META-INF/mods.toml') {
        expand version: inputs.properties.version
    }
}

/////////////
// Spotless
spotless {
    java {
        target("src/main/java/**/*.java")

        endWithNewline()
        leadingTabsToSpaces()
        removeUnusedImports()
        toggleOffOn()
        eclipse().configFile(file("codeformat/codeformat.xml"))
        importOrderFile(file("codeformat/ae2.importorder"))
    }

    format("json") {
        target("src/main/resources/**/*.json")
        prettier().config(parser: "json")
    }
}
