minecraft_version=1.20.1
fabric_loader_version=0.17.2
ae2_version=15.4.8
guideme_version=20.1.15
jei_version=15.20.0.113
rei_version=12.1.785
emi_version=1.1.22+1.20.1

fabric_api_version=0.92.6+1.20.1
botania_version_fabric=450-FABRIC

forge_version=1.20.1-47.4.6
botania_version_forge=450-FORGE
patchouli_version=84.1
curios_version=5.14.1

org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
