parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
neo_version=21.1.234
mod_id=appbot

ae2_version=19.2.17
botania_version=455-20260804.063319-46
jei_version=19.27.0.340
emi_version=1.1.24+1.21.1
jei_ae2_integration_id=7727898
jade_id=7545219

org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
